name: Python Application

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Check out repository
        uses: actions/checkout@v3

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'  # Use a stable Python version like 3.10 or 3.11

      # Step 3: Install system dependencies
      - name: Install system dependencies
        run: sudo apt-get install -y build-essential libffi-dev python3-dev

      # Step 4: Install Python dependencies
      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-timeout flake8
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 5: Lint with flake8
      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 . --exclude=.venv --count --select=E9,F63,F7,F82 --show-source --statistics


      # Step 6: Test with pytest
      - name: Test with pytest
        run: |
          pytest -v --maxfail=1 --timeout=30 --disable-warnings
